//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hims2
    {
        public int id { get; set; }
        public string HOUSING_PROGRAM { get; set; }
        public Nullable<int> ProjUniqueID { get; set; }
        public Nullable<int> ProjectNo { get; set; }
        public string PROJECT_STATUS { get; set; }
        public string PROJECT_INFO { get; set; }
        public string APN { get; set; }
        public Nullable<int> HouseId { get; set; }
        public string HouseNum { get; set; }
        public string HouseFracNum { get; set; }
        public string PIN { get; set; }
        public Nullable<int> CouncilDistrict { get; set; }
        public string PreDirCd { get; set; }
        public string StreetName { get; set; }
        public string StreetTypeCd { get; set; }
        public string PostDirCd { get; set; }
        public string UnitRange { get; set; }
        public string Unit_Number { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string City { get; set; }
        public Nullable<int> LAHD_Count { get; set; }
        public Nullable<int> LUPAM_Count { get; set; }
        public string IsInFloodZone { get; set; }
        public Nullable<int> CensusTract { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> AddressMasterId { get; set; }
    }
}
