//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prop_site_address2
    {
        public int id { get; set; }
        public long Apn { get; set; }
        public Nullable<int> HouseID { get; set; }
        public string Pin { get; set; }
        public Nullable<int> HouseNum { get; set; }
        public string HouseFracNum { get; set; }
        public string PreDirCd { get; set; }
        public string StreetName { get; set; }
        public string StreetTypeCd { get; set; }
        public string PostDirCd { get; set; }
        public string UnitRange { get; set; }
        public string City { get; set; }
        public Nullable<int> Zip { get; set; }
        public Nullable<short> ZipSuffix { get; set; }
        public Nullable<decimal> XCoord { get; set; }
        public Nullable<decimal> YCoord { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Lat { get; set; }
        public string Pind { get; set; }
        public string EngDist { get; set; }
        public Nullable<byte> CouncilDistrict { get; set; }
        public string LupLandUseCd { get; set; }
        public Nullable<bool> FlgHistMonument { get; set; }
        public Nullable<short> LutCodeOfficeCd { get; set; }
        public Nullable<short> LutRentAreaCd { get; set; }
        public Nullable<short> LutHistPresZoneCd { get; set; }
        public Nullable<int> TbmPage { get; set; }
        public Nullable<int> TbmRow { get; set; }
        public string TbmCol { get; set; }
        public Nullable<int> CenTract2010 { get; set; }
        public string CenBlock2010GeoID { get; set; }
        public string CenBlock2010 { get; set; }
        public string CenBlockGrp2010 { get; set; }
        public string CommunityName { get; set; }
        public Nullable<bool> FlgInsideCoi { get; set; }
        public string CraRedevCd { get; set; }
        public Nullable<int> StateAssemDist { get; set; }
        public Nullable<int> StateSenDist { get; set; }
        public Nullable<int> UsCongDist { get; set; }
        public Nullable<int> CountySupDistNum { get; set; }
        public Nullable<int> CommunityPlanAreaID { get; set; }
        public Nullable<int> NeighborhoodCouncilID { get; set; }
        public Nullable<bool> FlgNsp1 { get; set; }
        public Nullable<bool> FlgNsp2 { get; set; }
        public Nullable<bool> FlgNsp3 { get; set; }
        public string HseAssignedCd { get; set; }
        public Nullable<bool> HseFlgDeleted { get; set; }
        public Nullable<bool> ApnFlgDeleted { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> AddressMasterId { get; set; }
    }
}
