//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rent2
    {
        public int id { get; set; }
        public long APN { get; set; }
        public string Property_Address { get; set; }
        public string Service_Date { get; set; }
        public string Land_Use_Code { get; set; }
        public Nullable<int> Unit_Count { get; set; }
        public Nullable<int> Exempted_Units { get; set; }
        public Nullable<int> RSO_Units { get; set; }
        public Nullable<int> Year_Built { get; set; }
        public string Category { get; set; }
        public Nullable<int> Council_District { get; set; }
        public string Secondary_Address { get; set; }
        public Nullable<int> houseID { get; set; }
        public string FC_NOTES { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<int> AddressMasterId { get; set; }
    }
}
