//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hcid_lookupEntities : DbContext
    {
        public hcid_lookupEntities()
            : base("name=hcid_lookupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bims2> bims2 { get; set; }
        public virtual DbSet<prop_site_address2> prop_site_address2 { get; set; }
        public virtual DbSet<rent2> rent2 { get; set; }
        public virtual DbSet<addressmaster2> addressmaster2 { get; set; }
        public virtual DbSet<hims2> hims2 { get; set; }
    }
}
